### ISSUE TITLE
Please have a look at the revised edition of the CBOR standard

### ISSUE THREAD

**Issue by cabo** [greglook/clj-cbor#16]
This is not an issue on your software, but:
I would like to point out that the upcoming editorial revision of RFC
7049, informally called “rfc7049bis”, is in working group last call
right now — if you can spare some time, please have a look at

https://cbor-wg.github.io/CBORbis/draft-ietf-cbor-7049bis.html

and submit any issues (including potential for further improvement of
the text) you might find, at

https://github.com/cbor-wg/CBORbis

Thank you.

Carsten Bormann

**Comment by greglook** [comment]
Will do - is there an easy way to see a diff from the current RFC?

**Comment by cabo** [comment]
There is:

https://tools.ietf.org/rfcdiff?url1=https://tools.ietf.org/rfc/rfc7049.txt&url2=https://cbor-wg.github.io/CBORbis/draft-ietf-cbor-7049bis.txt

Because of the extensive editorial changes and some moving around, this is only partially useful, I'm afraid.

**Comment by cabo** [comment]
Well, there are still quite a few references to RFC 7049, including the README.
